name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Generate Release Notes from Commits
        run: |
          tag="${{ github.ref_name }}"
          
          # 이전 태그 찾기
          previous_tag=$(git tag --sort=-version:refname | grep -v "^$tag$" | head -n1)
          
          if [ -n "$previous_tag" ]; then
            echo "## Release $tag" > release-notes.md
            echo "" >> release-notes.md
            echo "### Changes since $previous_tag" >> release-notes.md
            echo "" >> release-notes.md
            git log --oneline "$previous_tag".."$tag" | sed 's/^/- /' >> release-notes.md
          else
            echo "## Release $tag" > release-notes.md
            echo "" >> release-notes.md
            echo "### Initial Release" >> release-notes.md
            echo "- First version of the plugin" >> release-notes.md
          fi
          
          echo "" >> release-notes.md
          echo "### Installation" >> release-notes.md
          echo "Download and install via BRAT or manually extract to your plugins folder." >> release-notes.md
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ github.ref_name }}"

          gh release create "$tag" \
            --title="$tag" \
            --notes-file="release-notes.md" \
            main.js manifest.json styles.css
